url: https://alxwen711.github.io
baseurl: /mathcampwebsite/
#remote_theme: agency-jekyll-theme

# Site settings
title: Alex's Math Camp
email: alxwen711@gmail.com
description: "An in person/online math program for students grades 6-9 led by Alex Wen delving into the interesting side of mathematics. Join today!"


# Team names, titles and social links
people:
- name: Alexander Wen
  pic: 1
  position: Lead Tutor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty